db:
  build: .
  dockerfile: Dockerfile-db
  volumes:
    - /database
web:
  build: .
  dockerfile: Dockerfile-concourse
  privileged: true
  links:
    - db
  command: /root/scripts/start.sh web
  ports:
    - "8080:8080"
  environment:
    CONCOURSE_LOGIN: '${CONCOURSE_LOGIN}'
    CONCOURSE_PASSWORD: '${CONCOURSE_PASSWORD}'
    CONCOURSE_EXTERNAL_URL: '${CONCOURSE_EXTERNAL_URL}'
worker:
  build: .
  dockerfile: Dockerfile-concourse
  privileged: true
  links:
    - web
    - db
  volumes:
    - /opt/concourse/worker
  command: /root/scripts/start.sh worker
